seed: 0

env:
  max_steps: 200
  scenario_name: "pursuit_formation_v3"
  scenario:
    n_agents: 4
  device: ??? # These values will be populated dynamically
  vmas_envs: ???

model:
  shared_parameters: False # MADDPG paper does not use shared params because reward function can be different
  centralised_critic: True # MADDPG if True, IDDPG if False

collector:
  frames_per_batch: 6_000 # Frames sampled each sampling iteration
  n_iters: 500 # Number of sampling/training iterations
  total_frames: ???

buffer:
  memory_size: ???

loss:
  gamma: 0.95
  tau: 0.005 # For target net

train:
  num_epochs: 45  # optimization steps per batch of data collected
  minibatch_size: 64 # size of minibatches used in each epoch
  lr: 1e-5
  max_grad_norm: 40.0
  device: ???

eval:
  evaluation_interval: 20
  evaluation_episodes: 200

logger:
  backend:  wandb # Delete to remove logging
  project_name: null
  group_name: null
