seed: 0
run_description: null
tags: []
checkpoint_path: "/workspace/torchrl/outputs/2025-06-05/01-07-00/snapshots/model_snapshot_iter_100.pt"
resume_training: True

env:
  max_steps: 500
  scenario_name: "potential_formation_movement"
  scenario:
    n_agents: 8
    shared_rew: True
  device: ??? # These values will be populated dynamically
  vmas_envs: ???

model:
  gnn_hidden_dim: 128
  gnn_layers: 2
  k_neighbors: 4  # Number of agents in observation space
  k_obstacles: 4  # Number of obstacles in observation space
  n_attention_heads: 4
  dropout: 0.1
  agent_pos_indices: [0,2]
  shared_parameters: True
  centralised_critic: True  # MAPPO if True, IPPO if False

collector:
  frames_per_batch: 12_000 # Frames sampled each sampling iteration
  n_iters: 500 # Number of sampling/training iterations
  total_frames: ???

buffer:
  memory_size: ???

loss:
  gamma: 0.995
  lmbda: 0.95
  entropy_eps: 0.1
  clip_epsilon: 0.2

train:
  num_epochs: 10  # optimization steps per batch of data collected
  minibatch_size: 100 # size of minibatches used in each epoch
  lr: 1e-4
  max_grad_norm: 0.5
  device: ???

eval:
  evaluation_interval: 10
  evaluation_episodes: 20

logger:
  backend: wandb # Delete to remove logging
  project_name: null
  group_name: null

snapshots:
  save_dir: saves
  save_best_only: False

