seed: 0

env:
  max_steps: 300
  scenario_name: "potential_formation_img"
  scenario:
    n_agents: 8
    shared_rew: True
  device: ??? # These values will be populated dynamically
  vmas_envs: ???

model:
  pgat_hidden_dim: 128
  pgat_layers: 2
  k_agents: 2  # Number of agents in observation space
  k_obstacles: 2  # Number of obstacles in observation space
  agent_feature_dim: 6  # Dimension of each agent's features
  obstacle_feature_dim: 4  # Dimension of each obstacle's features
  agent_attenuation: 1.0
  obstacle_attenuation: 1.0
  shared_parameters: True
  centralised_critic: True  # MAPPO if True, IPPO if False
  k_neighbours: 2
  pos_indices: [0, 2]
  gnn_hidden_dim: 128
  gnn_layers: 2

collector:
  frames_per_batch: 6_000 # Frames sampled each sampling iteration
  n_iters: 500 # Number of sampling/training iterations
  total_frames: ???

buffer:
  memory_size: ???

loss:
  gamma: 0.99
  lmbda: 0.9
  entropy_eps: 0
  clip_epsilon: 0.2

train:
  num_epochs: 45  # optimization steps per batch of data collected
  minibatch_size: 20 # size of minibatches used in each epoch
  lr: 5e-6
  max_grad_norm: 40.0
  device: ???

eval:
  evaluation_interval: 10
  evaluation_episodes: 200

logger:
  backend: wandb # Delete to remove logging
  project_name: null
  group_name: null

snapshots:
  save_dir: saves
  save_best_only: False

