seed: 0

env:
  max_steps: 200
  scenario_name: "pursuit_formation_v2"
  scenario:
    n_agents: 4
  device: ??? # These values will be populated dynamically
  vmas_envs: ???

model:
  shared_parameters: True
  centralised_critic: True  # MAPPO if True, IPPO if False

collector:
  frames_per_batch: 6_000 # Frames sampled each sampling iteration
  n_iters: 500 # Number of sampling/training iterations
  total_frames: ???

buffer:
  memory_size: ???

loss:
  gamma: 0.99
  lmbda: 0.9
  entropy_eps: 0
  clip_epsilon: 0.2

train:
  num_epochs: 45  # optimization steps per batch of data collected
  minibatch_size: 20 # size of minibatches used in each epoch
  lr: 1e-6
  max_grad_norm: 40.0
  device: ???

eval:
  evaluation_interval: 20
  evaluation_episodes: 200

logger:
  backend: wandb # Delete to remove logging
  project_name: null
  group_name: null
